MTGCards/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mainapp/', include('mainapp.urls', namespace = "mainapp")),
    url(r'^useritems/', include('useritems.urls', namespace = "useritems")),
    url(r'^trading/', include('trading.urls', namespace = "trading")),
]

mainapp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^signup/$', views.usersignup, name="signup"),
    url(r'^login/$', views.userlogin, name="login"),
    url(r'^logout/$', views.userlogout, name="logout"),
    url(r'^home/$', views.post_home, name="home"),
    url(r'^listofcards/$', views.list_of_cards, name="listofcards"),
]

trading/urls.py
from django.conf.urls import url
from . import views



urlpatterns = [

    url(r'^allcarts/$', views.allcarts, name="allcarts"),




]

useritems/urls.py
from django.conf.urls import url
from . import views



urlpatterns = [

    url(r'^mycart/$', views.mycart, name="mycart"),




]

mainapp/models.py
from django.db import models



class Cards(models.Model):
	name = models.CharField(max_length=300)
	text = models.TextField(null=True)
	image= models.URLField(max_length=300,null=True)

	def __str__(self):
		return self.name

trading/models.py
from django.db import models

# Create your models here.

useritems/models.py
from django.db import models
from mainapp.models import Cards
from django.contrib.auth.models import User


class CartItem(models.Model):
	cart = models.ForeignKey("Cart")
	items = models.ForeignKey(Cards)
	quantity = models.PositiveIntegerField(default=1)
	def __str__(self):
		return self.items.name



class Cart(models.Model):
	user = models.ForeignKey(User)
	items = models.ManyToManyField(Cards , through=CartItem)
	def __str__(self):
		return self.user.username

mainapp/forms.py
from django import forms
from django.contrib.auth.models import User 



class UserSignUp(forms.ModelForm):
	class Meta:
		model = User
		fields = ['username','password']
		widgets= {
			'password': forms.PasswordInput(),
		}
class UserLogin(forms.Form):
	username= forms.CharField(required=True)
	password= forms.CharField(required=True,widget=forms.PasswordInput())

mainapp/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate , login ,logout
from .forms import UserSignUp ,UserLogin 
from django.shortcuts import render, redirect
from mainapp.models import Cards
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q






def list_of_cards(request):
    details = Cards.objects.all()
    query = request.GET.get("q")
    if query:
        details= details.filter(
            Q(name__icontains=query) | 
            Q(text__icontains=query) 
            ).distinct()
        paginator = Paginator(details, 10) # Show 25 contacts per page

        page = request.GET.get('page')
        try:
            contacts = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            contacts = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            contacts = paginator.page(paginator.num_pages)
        context = {
        "list" : contacts ,
        "user": request.user,
        }
    else:
        paginator = Paginator(details, 10) # Show 25 contacts per page

        page = request.GET.get('page')
        try:
            contacts = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            contacts = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            contacts = paginator.page(paginator.num_pages)
        context = {
        "list" : contacts ,
        "user": request.user,
        }
    return render(request , 'listofcards.html' , context)



























#  the login and signup stuff 


def userlogin(request):
    context={}
    form = UserLogin()
    context['form'] = form 
    if request.method == "POST":
        form = UserLogin(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            auth_user= authenticate(username=username,password=password)
            if auth_user is not None:
                login(request,auth_user)
                return redirect("mainapp:home")

            messages.warning(request,"wrong user name or password")
            return redirect("mainapp:login")
        messages.warning(request,form.errors)
        return redirect("mainapp:login")
    return render(request, 'login.html',context)


def usersignup(request):
    context={}
    form = UserSignUp()
    context['form'] = form 
    if request.method == "POST":
        form = UserSignUp(request.POST)
        if form.is_valid():
            user = form.save()
            username = user.username
            password = user.password
            user.set_password(password)
            user.save()
            auth_user= authenticate(username=username,password=password)
            login(request,auth_user)
            return redirect("mainapp:home")
        messages.error(request,form.errors)
        return redirect("mainapp:signup")
    return render(request, 'signup.html',context)

def userlogout(request):
    logout(request)
    return redirect("mainapp:home")

def post_home(request):
   
    context = {
    "user": request.user,
    }
    return render(request, 'home.html', context)

trading/views.py
from django.shortcuts import render
from useritems.models import Cart



def allcarts(request):
	carts = Cart.objects.all()
	context = {
	"user": request.user,
	"carts":carts,

	}
	return render(request, 'allcarts.html',context)

useritems/views.py
from django.shortcuts import render
from .models import  *
from mainapp.models import Cards


def mycart(request):
	cart ,created = Cart.objects.get_or_create(user=request.user)
	item_id = request.GET.get("item")
	qty = request.GET.get("qty" , 1)

	if item_id:
		cards = Cards.objects.get(id=item_id)
		cart_item,created = CartItem.objects.get_or_create(cart=cart,items=cards)
		if int(qty)<1:
			cart_item.delete()
		else:
			cart_item.quantity = int(qty)
			cart_item.save()

	context ={
		'cart': cart,
		'user':request.user
	}


	return render(request, 'cart.html',context)

mainapp/templates/allcarts.html
{% extends "base.html" %}
{% block head_title %}All collection{% endblock head_title %}

{% block content %}

<div class="row">
{% for x in carts %}

		<div class="col-sm-4">
			<p>
			<button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#{{x.user}}" aria-expanded="false" aria-controls="{{x.user}}">
			    {{x.user}}
			  </button>
			</p>
			<div class="collapse" id="{{x.user}}">
			  <div class="card card-body">
			   	{% for y in x.cartitem_set.all %}
				<p>{{y.items.name}}</p>
				<img src="{{y.items.image}}" alt="{{y.items.name}}">
				<p>{{y.quantity}}</p>
				{% endfor %}
				</div>
		  </div>
</div>
{% endfor %}
</div>
{% endblock content%}

mainapp/templates/base.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
	<title>
		{% block head_title %}
		{% endblock head_title %}
	</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>

<body>		
	 <div class="container">
        {% include "navbar.html" %}
	{% block content %}



	{% endblock content%}
	</div>




   <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
	
</body>

</html>

mainapp/templates/home.html
{% extends "base.html" %}
{% block head_title %}Home{% endblock head_title %}

{% block content %}
<h1>{{user}}</h1>
<h3>hello user to your personal hell </h3>

{% endblock content%}

mainapp/templates/listofcards.html
{% extends "base.html" %}
{% block head_title %}list of cards{% endblock head_title %}   

{% block content %}
{% for x in list %}
	<div class="jumbotron">

	<h4>{{x.name}}</h4>
	<p>{{x.text}}</p>
	<img src="{{x.image}}" alt="{{x.name}}" >
	<form action="{% url 'useritems:mycart' %}" method="GET"> 
							<input type="hidden" name="item" value="{{x.id}}">
							<input type="number" name="qty" value="1" placeholder="Quntity">
							<input type="submit" class="btn btn-success" value="Add to cart">
						</form>
	</div>
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if list.has_previous %}
            <a href="?page={{ list.previous_page_number }}&q={{request.GET.q}}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ list.number }} of {{ list.paginator.num_pages }}.
        </span>

        {% if list.has_next %}
            <a href="?page={{ list.next_page_number }}&q={{request.GET.q}}">next</a>
        {% endif %}
    </span>
</div>
{% endblock content%}

mainapp/templates/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
	{% block head_title %}login
	{% endblock head_title %}

	<form method="POST" action="{% url 'mainapp:login'  %}" enctype="multipart/form-data">
		{% csrf_token %}
		{{form|crispy}}
		<input type="submit" value="login">
	</form>
{% endblock content%}

mainapp/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'mainapp:home'  %}">Main App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'mainapp:home'  %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'mainapp:login'  %}">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'mainapp:signup'  %}">Signup</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'mainapp:logout'  %}">Logout</a>
      </li>
    {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'useritems:mycart'  %}">My Collections</a>
      </li>
       <li class="nav-item">
        <a class="nav-link" href="{% url 'trading:allcarts'  %}">List of users and there cards</a>
      </li>
      {% endif %}
    </ul>
    <form class="navbar-form navbar-left" action="{% url 'mainapp:listofcards'  %}" method="GET">
        <div class="form-group">
          <input type="text" name="q" id="search_bar" placeholder="Search cards here" value="{{request.GET.q}}">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
</nav>
 
  </div>
</nav>

mainapp/templates/signup.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
	{% block head_title %}signup
	{% endblock head_title %}

	<form method="POST" action="{% url 'mainapp:signup'  %}" enctype="multipart/form-data">
		{% csrf_token %}
		{{form|crispy}}
		<input type="submit" value="signup">
	</form>
{% endblock content%}

useritems/templates/cart.html
{% extends "base.html" %}
{% block head_title %}Collection{% endblock head_title %}   
{% block content %}
<div class="row">
  
      <div class="card-group">
            
              
            
             
              
         {% for item  in cart.cartitem_set.all %}
          <div class="col-sm-4">
              <div class="card" style="width: 20em;">
                <img class="card-img-top" src="{{item.items.image}}" alt="{{item.items.name}}">
                <div class="card-body">
                  <h4 class="card-title">{{item.items.name}}</h4>
                  
                  <form action="{% url 'useritems:mycart' %}" method="GET"> 
                    <input type="hidden" name="item" value="{{item.items.id}}">
                    <input type="number" name="qty" value="{{item.quantity}}">
                    <input type="submit" class="btn btn-warning" value="Update Item">
                  </form>
                </div>
          </div>
              </div>
         {% endfor %}
          

        
        
    </div>
</div>

{% endblock content%}